apiVersion: v1
data:
  mysql-password: cGFzcw==
  mysql-root-password: cm9vdHBhc3M=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: training-system-web
    meta.helm.sh/release-namespace: training-system
  creationTimestamp: "2022-11-12T12:20:48Z"
  labels:
    app.kubernetes.io/instance: training-system-web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.1
  name: training-system-web-mysql
  namespace: training-system
  resourceVersion: "5782"
  uid: 7f844ce7-e201-49d4-b009-4225999f683a
type: Opaque



