name: Deploy

on:
  push:
    branches:
      - master
env:
  image_repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}
  image_tag: ${GITHUB_SHA::6}

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if docker image existed
        id: existed
        run: docker manifest inspect ${{ env.image_repository }}:${{ env.image_tag }}
        continue-on-error: true
      
      - name: Set up Docker Buildx
        if: steps.existed.outcome == 'failure'
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: steps.existed.outcome == 'failure'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: production
          tags: ${{ env.image_repository }}:${{ env.image_tag }}
          cache-from: type=registry,ref=${{ env.image_repository }}:buildcache
          cache-to: type=registry,ref=${{ env.image_repository }}:buildcache,mode=max
  deploy:
    needs: build
    name: Trigger pipeline Azure devops
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: alexrster/pipelines@v2
        with:
          azure-devops-project-url: http://uetbc.xyz:8888/DefaultCollection/Chuyen%20de%20Nhat%20Bon
          azure-pipeline-name: 'Training-system-web'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables: '{"TAG": "${{ env.image_tag }}", "IMAGE_REPOSITORY" : "${{ env.image_repository }}"}'